# Generated by Django 4.2.3 on 2024-02-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='leader_id',
            field=models.IntegerField(null=True),
        ),
    ]
