# Generated by Django 5.0.3 on 2024-05-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_app', '0002_alter_class_leader_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('class_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
                ('leader', models.BooleanField(default=False)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Class',
            new_name='Group',
        ),
    ]
