# Generated by Django 5.0.6 on 2024-05-25 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0003_remove_group_leader_remove_groupmember_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='leader_id',
            new_name='staff_ids',
        ),
    ]
