# Generated by Django 5.0.3 on 2024-05-08 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0002_alter_group_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='leader',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='age',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='leader',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='groups',
        ),
        migrations.AddField(
            model_name='group',
            name='leader_id',
            field=models.ManyToManyField(blank=True, to='staff_app.staff'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff_app.group'),
        ),
    ]
